---
title: "Reading Data From the Web"
author: "Jeff Goldsmith"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(httr)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## NSDUH data

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html = read_html(url)
```

```{r}
drug_use_html %>% 
  html_table() %>% 
  first()  %>%  ## html_table() pulls out all of the tables in the html. first() gives us the first from the list.
  slice(-1) ## minus 1st row
```

## SW data

```{r}
url = "https://www.imdb.com/list/ls070150896/"

swm_html = read_html(url)
```

How do I get the stuff I want?

```{r}
swm_titles = 
  swm_html %>% 
  html_elements(".lister-item-header a") %>% 
  html_text()
```

```{r}
swm_runtime = 
  swm_html %>% 
  html_elements(".runtime") %>% 
  html_text()
```

```{r}
swm_money = 
  swm_html %>% 
  html_elements(".text-muted .ghost~ .text-muted+ span") %>% 
  html_text()
```

```{r}
swm_df = 
  tibble(
    title = swm_titles,
    rev = swm_money,
    runtime = swm_runtime)
```

LA:

```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = 
  dynamite_html %>%
  html_elements(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_elements("#cm_cr-review_list .review-rating") %>%
  html_text()

review_text = 
  dynamite_html %>%
  html_elements(".review-text-content span") %>%
  html_text()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)

reviews
```

## APIs

```{r}
water_df = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") %>% 
  content("parsed")


```

Don't do this 
```{r eval = FALSE}
GET("https://data.cityofnewyork.us/resource/ia2d-e54m.json") %>% 
  content("text") 
```

```{r}
brfss_df = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",  
       query = list("$limit" = 5000)) %>%
  content("parsed")
```

```{r}
poke = 
  GET("http://pokeapi.co/api/v2/pokemon/1") %>%
  content()

names(poke)
poke[["species"]]
poke[["stats"]]
```

